### ISSUE TITLE
Compress as zip instat of 7z

### ISSUE THREAD

**Issue by klausenbusk** [lachs0r/mingw-w64-cmake#18]
Hello
Could you consider compress the binary as zip (or tar) or something more used?
I need to install new install programs to decompress 7z files, where zip in working out-of-the-box on windows, and tar on most Linux distro.

Not a big problem, just my 2 cent.

-- Kristian

**Comment by lachs0r** [comment]
No. Besides, you’re going to need an archiver that supports more than just zip at some point anyway. I guess “something more widely used” would be RAR, but switching to that now doesn’t make sense either, as WinRAR supports 7z.

I am considering a minimal updater/installer though (only downloads and unpacks the current build, optionally installs it and registers file types for current user).
