### ISSUE TITLE
rst2pdf lost

### ISSUE THREAD

**Issue by phantomgz** [lachs0r/mingw-w64-cmake#21]
I found when compile mpv packege, when run in step of configure, the configure complain library rst2pdf not found, so I have to disable this option in mpv.conf, after this,  I sucess to compiling the packege of mpv-prefix.
  after compile I looking in package/mpv-dev, all  the *.dll and *.a exist, and mpv.exe/mpv.com place in package/mpv-package , but where I can find the include file like *.h *.hpp and *.pc, why not copy to mpv-dev directory.

thanks.

**Comment by lachs0r** [comment]
Well, install it, then?
