### ISSUE TITLE
Add --disable-debug-build to your config

### ISSUE THREAD

**Issue by zxx1** [lachs0r/mingw-w64-cmake#23]
I made some tests and build with --disable-debug-build had 2-6% lower CPU usage and ~5mb smaller file size than your build.

**Comment by lachs0r** [comment]
On Saturday 02 January 2016 02:15:54 zxx1 wrote:
> I made some tests and build with --disable-debug-build had 2-6% lower CPU
> usage and ~5mb smaller file size than your build

Placebo, also useless numbers (you acquire real numbers using a profiler,
not your task manager), etc.

That option changes absolutely nothing except for the inclusion of debug 
symbols (see waftools/detections/compiler.py). Running strip on the executable 
should result in the same file size if the build environment was identical.

Debug symbols are necessary for the -dev archives to be useful for debugging.

**Comment by zxx1** [comment]
Process Monitor (Options->Profiling events) isn't good enough for the measurement? Also I made a shared build, without debug info its size ~2 mb, the same as on Linux, with debug it's around 7.5 mb.
