### ISSUE TITLE
No licence?

### ISSUE THREAD

**Issue by rfree-d** [lachs0r/mingw-w64-cmake#25]
This projects seems to lack a licence/license information in it.

@lachs0r what are the terms of using this code (e.g. we would like to copy some files from there to other project, e.g. one that is now on GPLv3 but in future would be on BSD 2/3/4-clasue or MPL 2.0 or mix of this licenses)?

**Comment by lachs0r** [comment]
ISC, so pretty much equivalent to 2-clause BSD. Happy copypasting.
