### ISSUE TITLE
angle build broken

### ISSUE THREAD

**Issue by nshtg** [lachs0r/mingw-w64-cmake#32]
The commit https://github.com/google/angle/commit/74a0000f514cfe521a3c865a441f7df841a14ca5 introduced the requirement for a file `<d3d11_3.h>` which mingw does not have so angle won't compile anymore.

Last working commit is now https://github.com/google/angle/commit/1a1ae0f85eb60bc287768d0e5a7e95c9514a787a.

**Comment by lachs0r** [comment]
ACK. Reverted to that commit for now.

What do you think will happen sooner? MinGW-w64 finally catching up to the 
Windows SDK headers or mpv getting proper Vulkan support? I’m already patching 
the DXGI 1.2/D3D 11.1 headers. Surprises me that those haven’t been merged 
yet.

**Comment by rossy** [comment]
I asked #videolan about this a while back, because they also have their own copies of DXGI headers. Apparently this is because mingw-w64 use the Direct3D headers from Wine and Wine are just slow because they are notoriously paranoid about accepting contributions that may have been derived from official Windows SDK headers.

It will be interesting to see what MSYS2 or Qt do to get around this issue if/when they update their version of ANGLE.

**Comment by DeadSix27** [comment]
@lachs0r @rossy i've also been just using patches for DXGI (and now use shinchiro's for d3d11_3)

But angle also requires `D3D11_STANDARD_MULTISAMPLE_PATTERN` now which is not in shins patch(es), you'll have to also patch d3d11.h now.

@rossy I tried finding a way to  just use videolans copies too but couldn't find them on their source tree, they seem to be generated in the contribs but I didn't want to build the entire contrib just for those

**Comment by rossy** [comment]
Yeah, VLC seems to just have the .idl files in their tree. You can generate headers for these with the widl tool that comes with mingw-w64 (which was originally Wine's IDL compiler.) widl also works on some of the .idl files in the Windows SDK and can generate code that works with mingw-w64's __uuidof implementation.

mpv might eventually need to do this in-tree if we want to support things like native HDR/10-bit output, which requires DXGI 1.5/1.6.

**Comment by nshtg** [comment]
You could consider taking over @shinchiro patches: https://github.com/shinchiro/mpv-winbuild-cmake/commit/8bff525e1c9cbf2551026d8f83c79d5001d429aa

**Comment by DeadSix27** [comment]
@nshtg Ye I mentioned that in my comment, he also lacks a change in d3d11.h tho

**Comment by nshtg** [comment]
shinchiro updated his patches, see https://github.com/shinchiro/mpv-winbuild-cmake/commit/fcf18e97cec858d67a573daafa22f32fd9c584ad

**Comment by shinchiro** [comment]
fyi, I already sent these patches to wine mailing and got accepted, including dxgi 1.4-1.6 so there's no need for these patches once mingw-w64 import the headers.

**Comment by rossy** [comment]
Oh nice. That's good news. This will also be helpful with ra_d3d11 (I've been wanting to use newer D3D11/DXGI features.)

**Comment by DeadSix27** [comment]
@shinchiro awesome, thanks!

**Comment by nshtg** [comment]
@lachs0r @rossy 
I think the changes have been merged upstream.
