### ISSUE TITLE
Outdated packages & download problems

### ISSUE THREAD

**Issue by xnoreq** [lachs0r/mingw-w64-cmake#33]
binutils 2.29.1
libgcrypt 1.8.1
fribidi - has moved to github?

and please change ftp and if possible http to https download links.

**Comment by lachs0r** [comment]
Fixed.

HTTPS doesn’t really make much of a difference since the hashes are known, but I did it anyway. Can’t hurt. Now if we could get git signature verification in CMake’s ExternalProject module …
